### ISSUE TITLE
Add a fez util to programmatically run commands against a target

### ISSUE THREAD

**Issue by philc** [dmac/fezzik#12]
e.g. fez to_staging run_command 'ls', instead of having to do it interactively through fez to_staging command.

**Comment by cespare** [comment]
This is possible right now.

```
fez staging command_execute\['ls'\]
```

You have to escape the `[]` somehow (at least when I tested it in zsh) so that's kind of lame. This is the standard (ugly) rake syntax for this kind of thing, however. I suppose we could do some hackery to consume subsequent command-line arguments, but it would be gross to code and unintuitive to people who already know rake.

I'll add a note of this to the readme.
