### ISSUE TITLE
Expose weave options

### ISSUE THREAD

**Issue by dmac** [dmac/fezzik#53]
Weave accepts some options, such as the number of concurrent connections to use, that fezzik doesn't yet take advantage of. There are a few ways we could expose this:
1. Global option
   
   ``` ruby
   Fezzik.num_threads = 20
   ```
2. Option on host task
   
   ``` ruby
   host_task :foo, :num_threads => 20 do
   end
   ```
3. General exposure of weave options
   
   ``` ruby
   host_task :foo, :weave_options => {:num_threads => 20} do
   end
   ```

Other weave options to potentially add are `:serial` and `:batch_by`.

**Comment by dmac** [comment]
Weave options are now allowed on the same level as `:deps`, `:args`, and `:roles`, and are passed along to the weave connection pool.

**Comment by cespare** [comment]
Cool, I like this. The third option looks the messiest but I think it's the best because (a) it's not magical (there's no translation of certain options to weave options) and (b) you probably won't be specifying these options very often.

Side note: do you now get rolling deploys for free by doing `:weave_options => { :batch_by => N, :num_threads => N }` on your deploy `host_task`?

**Comment by dmac** [comment]
Almost. If you have the common setup of a single `:deploy` task that has many `:host_task`s as dependencies, you couldn't (for example) add those options to the top level `:deploy` task.

You can, however, add them to your restart task, and you're basically good.

**Comment by cespare** [comment]
Oh, will those settings not recursively apply? It seems like they should.

**Comment by dmac** [comment]
I meant that you can't specify them on `task`, just `host_task`.
